# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_Window_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main_Window_UI(object):
    def setupUi(self, Main_Window_UI):
        Main_Window_UI.setObjectName("Main_Window_UI")
        Main_Window_UI.setEnabled(True)
        Main_Window_UI.resize(1481, 961)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Main_Window_UI.sizePolicy().hasHeightForWidth())
        Main_Window_UI.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(109, 109, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 113, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(109, 109, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 113, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 113, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(113, 113, 113))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Main_Window_UI.setPalette(palette)
        Main_Window_UI.setFocusPolicy(QtCore.Qt.ClickFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("res/Icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Main_Window_UI.setWindowIcon(icon)
        self.Main_Layout = QtWidgets.QWidget(Main_Window_UI)
        self.Main_Layout.setObjectName("Main_Layout")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Main_Layout)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Image_Layout = QtWidgets.QVBoxLayout()
        self.Image_Layout.setSpacing(0)
        self.Image_Layout.setObjectName("Image_Layout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Image_Lable = QLable_File_Dragable(self.Main_Layout)
        self.Image_Lable.setMinimumSize(QtCore.QSize(1, 1))
        self.Image_Lable.setAcceptDrops(True)
        self.Image_Lable.setPixmap(QtGui.QPixmap("res/TransparentBg-W.png"))
        self.Image_Lable.setScaledContents(True)
        self.Image_Lable.setObjectName("Image_Lable")
        self.horizontalLayout_2.addWidget(self.Image_Lable)
        self.Image_V_Scrollbar = QtWidgets.QScrollBar(self.Main_Layout)
        self.Image_V_Scrollbar.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Image_V_Scrollbar.sizePolicy().hasHeightForWidth())
        self.Image_V_Scrollbar.setSizePolicy(sizePolicy)
        self.Image_V_Scrollbar.setObjectName("Image_V_Scrollbar")
        self.horizontalLayout_2.addWidget(self.Image_V_Scrollbar)
        self.Image_Layout.addLayout(self.horizontalLayout_2)
        self.Image_H_Scrollbar = QtWidgets.QScrollBar(self.Main_Layout)
        self.Image_H_Scrollbar.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Image_H_Scrollbar.sizePolicy().hasHeightForWidth())
        self.Image_H_Scrollbar.setSizePolicy(sizePolicy)
        self.Image_H_Scrollbar.setOrientation(QtCore.Qt.Horizontal)
        self.Image_H_Scrollbar.setObjectName("Image_H_Scrollbar")
        self.Image_Layout.addWidget(self.Image_H_Scrollbar)
        self.horizontalLayout.addLayout(self.Image_Layout)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.Control_Panel_Layout = QtWidgets.QVBoxLayout()
        self.Control_Panel_Layout.setContentsMargins(-1, 15, -1, 15)
        self.Control_Panel_Layout.setSpacing(0)
        self.Control_Panel_Layout.setObjectName("Control_Panel_Layout")
        self.Color_Layout = QtWidgets.QHBoxLayout()
        self.Color_Layout.setSpacing(15)
        self.Color_Layout.setObjectName("Color_Layout")
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Color_Layout.addItem(spacerItem2)
        self.Color_Preview_Lable = QtWidgets.QLabel(self.Main_Layout)
        self.Color_Preview_Lable.setText("")
        self.Color_Preview_Lable.setPixmap(QtGui.QPixmap("res/Transparent_Lable.png"))
        self.Color_Preview_Lable.setScaledContents(True)
        self.Color_Preview_Lable.setObjectName("Color_Preview_Lable")
        self.Color_Layout.addWidget(self.Color_Preview_Lable)
        self.Color_Setting_Layout = QtWidgets.QVBoxLayout()
        self.Color_Setting_Layout.setSpacing(7)
        self.Color_Setting_Layout.setObjectName("Color_Setting_Layout")
        self.R_Layout = QtWidgets.QHBoxLayout()
        self.R_Layout.setSpacing(5)
        self.R_Layout.setObjectName("R_Layout")
        self.R_Lable = QtWidgets.QLabel(self.Main_Layout)
        self.R_Lable.setObjectName("R_Lable")
        self.R_Layout.addWidget(self.R_Lable)
        self.R_Scrollbar = QtWidgets.QScrollBar(self.Main_Layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R_Scrollbar.sizePolicy().hasHeightForWidth())
        self.R_Scrollbar.setSizePolicy(sizePolicy)
        self.R_Scrollbar.setMaximum(255)
        self.R_Scrollbar.setProperty("value", 255)
        self.R_Scrollbar.setOrientation(QtCore.Qt.Horizontal)
        self.R_Scrollbar.setObjectName("R_Scrollbar")
        self.R_Layout.addWidget(self.R_Scrollbar)
        self.R_LineEdit = QtWidgets.QLineEdit(self.Main_Layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.R_LineEdit.sizePolicy().hasHeightForWidth())
        self.R_LineEdit.setSizePolicy(sizePolicy)
        self.R_LineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.R_LineEdit.setStyleSheet("color:white;\n"
"background-color:rgb(70 , 70 , 70);\n"
"border: 1px solid rgb(28 , 28 , 28);")
        self.R_LineEdit.setObjectName("R_LineEdit")
        self.R_Layout.addWidget(self.R_LineEdit)
        self.Color_Setting_Layout.addLayout(self.R_Layout)
        self.G_Layout = QtWidgets.QHBoxLayout()
        self.G_Layout.setSpacing(5)
        self.G_Layout.setObjectName("G_Layout")
        self.G_Lable = QtWidgets.QLabel(self.Main_Layout)
        self.G_Lable.setObjectName("G_Lable")
        self.G_Layout.addWidget(self.G_Lable)
        self.G_Scrollbar = QtWidgets.QScrollBar(self.Main_Layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G_Scrollbar.sizePolicy().hasHeightForWidth())
        self.G_Scrollbar.setSizePolicy(sizePolicy)
        self.G_Scrollbar.setMaximum(255)
        self.G_Scrollbar.setProperty("value", 255)
        self.G_Scrollbar.setOrientation(QtCore.Qt.Horizontal)
        self.G_Scrollbar.setObjectName("G_Scrollbar")
        self.G_Layout.addWidget(self.G_Scrollbar)
        self.G_LineEdit = QtWidgets.QLineEdit(self.Main_Layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.G_LineEdit.sizePolicy().hasHeightForWidth())
        self.G_LineEdit.setSizePolicy(sizePolicy)
        self.G_LineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.G_LineEdit.setStyleSheet("color:white;\n"
"background-color:rgb(70 , 70 , 70);\n"
"border: 1px solid rgb(28 , 28 , 28);")
        self.G_LineEdit.setObjectName("G_LineEdit")
        self.G_Layout.addWidget(self.G_LineEdit)
        self.Color_Setting_Layout.addLayout(self.G_Layout)
        self.B_Layout = QtWidgets.QHBoxLayout()
        self.B_Layout.setSpacing(5)
        self.B_Layout.setObjectName("B_Layout")
        self.B_Lable = QtWidgets.QLabel(self.Main_Layout)
        self.B_Lable.setObjectName("B_Lable")
        self.B_Layout.addWidget(self.B_Lable)
        self.B_Scrollbar = QtWidgets.QScrollBar(self.Main_Layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B_Scrollbar.sizePolicy().hasHeightForWidth())
        self.B_Scrollbar.setSizePolicy(sizePolicy)
        self.B_Scrollbar.setMaximum(255)
        self.B_Scrollbar.setProperty("value", 255)
        self.B_Scrollbar.setOrientation(QtCore.Qt.Horizontal)
        self.B_Scrollbar.setObjectName("B_Scrollbar")
        self.B_Layout.addWidget(self.B_Scrollbar)
        self.B_LineEdit = QtWidgets.QLineEdit(self.Main_Layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.B_LineEdit.sizePolicy().hasHeightForWidth())
        self.B_LineEdit.setSizePolicy(sizePolicy)
        self.B_LineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.B_LineEdit.setStyleSheet("color:white;\n"
"background-color:rgb(70 , 70 , 70);\n"
"border: 1px solid rgb(28 , 28 , 28);")
        self.B_LineEdit.setObjectName("B_LineEdit")
        self.B_Layout.addWidget(self.B_LineEdit)
        self.Color_Setting_Layout.addLayout(self.B_Layout)
        self.A_Layout = QtWidgets.QHBoxLayout()
        self.A_Layout.setSpacing(5)
        self.A_Layout.setObjectName("A_Layout")
        self.A_Lable = QtWidgets.QLabel(self.Main_Layout)
        self.A_Lable.setObjectName("A_Lable")
        self.A_Layout.addWidget(self.A_Lable)
        self.A_Scrollbar = QtWidgets.QScrollBar(self.Main_Layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A_Scrollbar.sizePolicy().hasHeightForWidth())
        self.A_Scrollbar.setSizePolicy(sizePolicy)
        self.A_Scrollbar.setMaximum(255)
        self.A_Scrollbar.setProperty("value", 255)
        self.A_Scrollbar.setOrientation(QtCore.Qt.Horizontal)
        self.A_Scrollbar.setObjectName("A_Scrollbar")
        self.A_Layout.addWidget(self.A_Scrollbar)
        self.A_LineEdit = QtWidgets.QLineEdit(self.Main_Layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.A_LineEdit.sizePolicy().hasHeightForWidth())
        self.A_LineEdit.setSizePolicy(sizePolicy)
        self.A_LineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.A_LineEdit.setStyleSheet("color:white;\n"
"background-color:rgb(70 , 70 , 70);\n"
"border: 1px solid rgb(28 , 28 , 28);")
        self.A_LineEdit.setObjectName("A_LineEdit")
        self.A_Layout.addWidget(self.A_LineEdit)
        self.Color_Setting_Layout.addLayout(self.A_Layout)
        self.Color_Layout.addLayout(self.Color_Setting_Layout)
        spacerItem3 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Color_Layout.addItem(spacerItem3)
        self.Color_Layout.setStretch(0, 1)
        self.Color_Layout.setStretch(3, 1)
        self.Control_Panel_Layout.addLayout(self.Color_Layout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.Control_Panel_Layout.addItem(spacerItem4)
        self.Working_Status_Label = QtWidgets.QLabel(self.Main_Layout)
        self.Working_Status_Label.setText("")
        self.Working_Status_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Working_Status_Label.setObjectName("Working_Status_Label")
        self.Control_Panel_Layout.addWidget(self.Working_Status_Label)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.Control_Panel_Layout.addItem(spacerItem5)
        self.Image_Count_Label = QtWidgets.QLabel(self.Main_Layout)
        self.Image_Count_Label.setText("")
        self.Image_Count_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Image_Count_Label.setObjectName("Image_Count_Label")
        self.Control_Panel_Layout.addWidget(self.Image_Count_Label)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.Control_Panel_Layout.addItem(spacerItem6)
        self.RBotton_Layout = QtWidgets.QHBoxLayout()
        self.RBotton_Layout.setContentsMargins(10, -1, -1, -1)
        self.RBotton_Layout.setObjectName("RBotton_Layout")
        spacerItem7 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.RBotton_Layout.addItem(spacerItem7)
        self.Cutout_RadioB = QtWidgets.QRadioButton(self.Main_Layout)
        self.Cutout_RadioB.setChecked(True)
        self.Cutout_RadioB.setObjectName("Cutout_RadioB")
        self.RBotton_Layout.addWidget(self.Cutout_RadioB)
        self.PickColor_RadioB = QtWidgets.QRadioButton(self.Main_Layout)
        self.PickColor_RadioB.setObjectName("PickColor_RadioB")
        self.RBotton_Layout.addWidget(self.PickColor_RadioB)
        self.Coloring_RadioB = QtWidgets.QRadioButton(self.Main_Layout)
        self.Coloring_RadioB.setObjectName("Coloring_RadioB")
        self.RBotton_Layout.addWidget(self.Coloring_RadioB)
        self.Filling_RadioB = QtWidgets.QRadioButton(self.Main_Layout)
        self.Filling_RadioB.setObjectName("Filling_RadioB")
        self.RBotton_Layout.addWidget(self.Filling_RadioB)
        spacerItem8 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.RBotton_Layout.addItem(spacerItem8)
        self.RBotton_Layout.setStretch(0, 1)
        self.RBotton_Layout.setStretch(5, 1)
        self.Control_Panel_Layout.addLayout(self.RBotton_Layout)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.Control_Panel_Layout.addItem(spacerItem9)
        self.T_Layout = QtWidgets.QHBoxLayout()
        self.T_Layout.setSpacing(10)
        self.T_Layout.setObjectName("T_Layout")
        spacerItem10 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.T_Layout.addItem(spacerItem10)
        self.T_Lable = QtWidgets.QLabel(self.Main_Layout)
        self.T_Lable.setObjectName("T_Lable")
        self.T_Layout.addWidget(self.T_Lable)
        self.T_Scrollbar = QtWidgets.QScrollBar(self.Main_Layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.T_Scrollbar.sizePolicy().hasHeightForWidth())
        self.T_Scrollbar.setSizePolicy(sizePolicy)
        self.T_Scrollbar.setMaximum(255)
        self.T_Scrollbar.setOrientation(QtCore.Qt.Horizontal)
        self.T_Scrollbar.setObjectName("T_Scrollbar")
        self.T_Layout.addWidget(self.T_Scrollbar)
        self.T_LineEdit = QtWidgets.QLineEdit(self.Main_Layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.T_LineEdit.sizePolicy().hasHeightForWidth())
        self.T_LineEdit.setSizePolicy(sizePolicy)
        self.T_LineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.T_LineEdit.setStyleSheet("color:white;\n"
"background-color:rgb(70 , 70 , 70);\n"
"border: 1px solid rgb(28 , 28 , 28);")
        self.T_LineEdit.setObjectName("T_LineEdit")
        self.T_Layout.addWidget(self.T_LineEdit)
        spacerItem11 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.T_Layout.addItem(spacerItem11)
        self.T_Layout.setStretch(0, 2)
        self.T_Layout.setStretch(4, 2)
        self.Control_Panel_Layout.addLayout(self.T_Layout)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.Control_Panel_Layout.addItem(spacerItem12)
        self.S_Layout = QtWidgets.QHBoxLayout()
        self.S_Layout.setSpacing(10)
        self.S_Layout.setObjectName("S_Layout")
        spacerItem13 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.S_Layout.addItem(spacerItem13)
        self.S_Lable = QtWidgets.QLabel(self.Main_Layout)
        self.S_Lable.setObjectName("S_Lable")
        self.S_Layout.addWidget(self.S_Lable)
        self.S_Scrollbar = QtWidgets.QScrollBar(self.Main_Layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.S_Scrollbar.sizePolicy().hasHeightForWidth())
        self.S_Scrollbar.setSizePolicy(sizePolicy)
        self.S_Scrollbar.setMinimum(1)
        self.S_Scrollbar.setMaximum(255)
        self.S_Scrollbar.setProperty("value", 1)
        self.S_Scrollbar.setOrientation(QtCore.Qt.Horizontal)
        self.S_Scrollbar.setObjectName("S_Scrollbar")
        self.S_Layout.addWidget(self.S_Scrollbar)
        self.S_LineEdit = QtWidgets.QLineEdit(self.Main_Layout)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.S_LineEdit.sizePolicy().hasHeightForWidth())
        self.S_LineEdit.setSizePolicy(sizePolicy)
        self.S_LineEdit.setMinimumSize(QtCore.QSize(50, 0))
        self.S_LineEdit.setStyleSheet("color:white;\n"
"background-color:rgb(70 , 70 , 70);\n"
"border: 1px solid rgb(28 , 28 , 28);")
        self.S_LineEdit.setObjectName("S_LineEdit")
        self.S_Layout.addWidget(self.S_LineEdit)
        spacerItem14 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.S_Layout.addItem(spacerItem14)
        self.S_Layout.setStretch(0, 2)
        self.S_Layout.setStretch(4, 2)
        self.Control_Panel_Layout.addLayout(self.S_Layout)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.Control_Panel_Layout.addItem(spacerItem15)
        self.Botton_Layout_2 = QtWidgets.QHBoxLayout()
        self.Botton_Layout_2.setObjectName("Botton_Layout_2")
        spacerItem16 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Botton_Layout_2.addItem(spacerItem16)
        self.Botton_Layout = QtWidgets.QVBoxLayout()
        self.Botton_Layout.setSpacing(25)
        self.Botton_Layout.setObjectName("Botton_Layout")
        self.WorkDir_Button = QtWidgets.QPushButton(self.Main_Layout)
        self.WorkDir_Button.setMinimumSize(QtCore.QSize(0, 28))
        self.WorkDir_Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.WorkDir_Button.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background-color:rgb(65 , 65 , 65);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:hover{\n"
"color:white;\n"
"background-color:rgb(75 , 75 , 75);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:pressed{\n"
"color:white;\n"
"background-color:rgb(85 , 85 , 85);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:disabled{\n"
"color:white;\n"
"background-color:rgb(95 , 95 , 95);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}")
        self.WorkDir_Button.setObjectName("WorkDir_Button")
        self.Botton_Layout.addWidget(self.WorkDir_Button)
        self.Revoke_Button = QtWidgets.QPushButton(self.Main_Layout)
        self.Revoke_Button.setMinimumSize(QtCore.QSize(0, 28))
        self.Revoke_Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Revoke_Button.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background-color:rgb(65 , 65 , 65);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:hover{\n"
"color:white;\n"
"background-color:rgb(75 , 75 , 75);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:pressed{\n"
"color:white;\n"
"background-color:rgb(85 , 85 , 85);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:disabled{\n"
"color:white;\n"
"background-color:rgb(95 , 95 , 95);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}")
        self.Revoke_Button.setObjectName("Revoke_Button")
        self.Botton_Layout.addWidget(self.Revoke_Button)
        self.Redo_Button = QtWidgets.QPushButton(self.Main_Layout)
        self.Redo_Button.setMinimumSize(QtCore.QSize(0, 28))
        self.Redo_Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Redo_Button.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background-color:rgb(65 , 65 , 65);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:hover{\n"
"color:white;\n"
"background-color:rgb(75 , 75 , 75);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:pressed{\n"
"color:white;\n"
"background-color:rgb(85 , 85 , 85);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:disabled{\n"
"color:white;\n"
"background-color:rgb(95 , 95 , 95);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}")
        self.Redo_Button.setObjectName("Redo_Button")
        self.Botton_Layout.addWidget(self.Redo_Button)
        self.Crop_Button = QtWidgets.QPushButton(self.Main_Layout)
        self.Crop_Button.setMinimumSize(QtCore.QSize(0, 28))
        self.Crop_Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Crop_Button.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background-color:rgb(65 , 65 , 65);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:hover{\n"
"color:white;\n"
"background-color:rgb(75 , 75 , 75);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:pressed{\n"
"color:white;\n"
"background-color:rgb(85 , 85 , 85);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:disabled{\n"
"color:white;\n"
"background-color:rgb(95 , 95 , 95);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}")
        self.Crop_Button.setObjectName("Crop_Button")
        self.Botton_Layout.addWidget(self.Crop_Button)
        self.Clean_Button = QtWidgets.QPushButton(self.Main_Layout)
        self.Clean_Button.setMinimumSize(QtCore.QSize(0, 28))
        self.Clean_Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Clean_Button.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background-color:rgb(65 , 65 , 65);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:hover{\n"
"color:white;\n"
"background-color:rgb(75 , 75 , 75);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:pressed{\n"
"color:white;\n"
"background-color:rgb(85 , 85 , 85);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:disabled{\n"
"color:white;\n"
"background-color:rgb(95 , 95 , 95);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}")
        self.Clean_Button.setObjectName("Clean_Button")
        self.Botton_Layout.addWidget(self.Clean_Button)
        self.Binarization_Button = QtWidgets.QPushButton(self.Main_Layout)
        self.Binarization_Button.setMinimumSize(QtCore.QSize(0, 28))
        self.Binarization_Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Binarization_Button.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background-color:rgb(65 , 65 , 65);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:hover{\n"
"color:white;\n"
"background-color:rgb(75 , 75 , 75);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:pressed{\n"
"color:white;\n"
"background-color:rgb(85 , 85 , 85);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:disabled{\n"
"color:white;\n"
"background-color:rgb(95 , 95 , 95);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}")
        self.Binarization_Button.setObjectName("Binarization_Button")
        self.Botton_Layout.addWidget(self.Binarization_Button)
        self.Full_Automatic_Button = QtWidgets.QPushButton(self.Main_Layout)
        self.Full_Automatic_Button.setMinimumSize(QtCore.QSize(0, 28))
        self.Full_Automatic_Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Full_Automatic_Button.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background-color:rgb(65 , 65 , 65);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:hover{\n"
"color:white;\n"
"background-color:rgb(75 , 75 , 75);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:pressed{\n"
"color:white;\n"
"background-color:rgb(85 , 85 , 85);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:disabled{\n"
"color:white;\n"
"background-color:rgb(95 , 95 , 95);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}")
        self.Full_Automatic_Button.setObjectName("Full_Automatic_Button")
        self.Botton_Layout.addWidget(self.Full_Automatic_Button)
        self.Semi_Automatic_Button = QtWidgets.QPushButton(self.Main_Layout)
        self.Semi_Automatic_Button.setMinimumSize(QtCore.QSize(0, 28))
        self.Semi_Automatic_Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Semi_Automatic_Button.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background-color:rgb(65 , 65 , 65);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:hover{\n"
"color:white;\n"
"background-color:rgb(75 , 75 , 75);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:pressed{\n"
"color:white;\n"
"background-color:rgb(85 , 85 , 85);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:disabled{\n"
"color:white;\n"
"background-color:rgb(95 , 95 , 95);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}")
        self.Semi_Automatic_Button.setObjectName("Semi_Automatic_Button")
        self.Botton_Layout.addWidget(self.Semi_Automatic_Button)
        self.Change_Background_Button = QtWidgets.QPushButton(self.Main_Layout)
        self.Change_Background_Button.setMinimumSize(QtCore.QSize(0, 28))
        self.Change_Background_Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Change_Background_Button.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background-color:rgb(65 , 65 , 65);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:hover{\n"
"color:white;\n"
"background-color:rgb(75 , 75 , 75);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:pressed{\n"
"color:white;\n"
"background-color:rgb(85 , 85 , 85);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:disabled{\n"
"color:white;\n"
"background-color:rgb(95 , 95 , 95);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}")
        self.Change_Background_Button.setObjectName("Change_Background_Button")
        self.Botton_Layout.addWidget(self.Change_Background_Button)
        self.Previous_Button = QtWidgets.QPushButton(self.Main_Layout)
        self.Previous_Button.setMinimumSize(QtCore.QSize(0, 28))
        self.Previous_Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Previous_Button.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background-color:rgb(65 , 65 , 65);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:hover{\n"
"color:white;\n"
"background-color:rgb(75 , 75 , 75);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:pressed{\n"
"color:white;\n"
"background-color:rgb(85 , 85 , 85);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:disabled{\n"
"color:white;\n"
"background-color:rgb(95 , 95 , 95);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}")
        self.Previous_Button.setObjectName("Previous_Button")
        self.Botton_Layout.addWidget(self.Previous_Button)
        self.Next_Button = QtWidgets.QPushButton(self.Main_Layout)
        self.Next_Button.setMinimumSize(QtCore.QSize(0, 28))
        self.Next_Button.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Next_Button.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background-color:rgb(65 , 65 , 65);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:hover{\n"
"color:white;\n"
"background-color:rgb(75 , 75 , 75);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:pressed{\n"
"color:white;\n"
"background-color:rgb(85 , 85 , 85);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:disabled{\n"
"color:white;\n"
"background-color:rgb(95 , 95 , 95);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}")
        self.Next_Button.setObjectName("Next_Button")
        self.Botton_Layout.addWidget(self.Next_Button)
        self.Save_Botton = QtWidgets.QPushButton(self.Main_Layout)
        self.Save_Botton.setMinimumSize(QtCore.QSize(0, 28))
        self.Save_Botton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Save_Botton.setStyleSheet("QPushButton{\n"
"color:white;\n"
"background-color:rgb(65 , 65 , 65);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:hover{\n"
"color:white;\n"
"background-color:rgb(75 , 75 , 75);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:pressed{\n"
"color:white;\n"
"background-color:rgb(85 , 85 , 85);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}\n"
"QPushButton:disabled{\n"
"color:white;\n"
"background-color:rgb(95 , 95 , 95);\n"
"border: 1px solid rgb(28 , 28 , 28);\n"
"}")
        self.Save_Botton.setObjectName("Save_Botton")
        self.Botton_Layout.addWidget(self.Save_Botton)
        self.Botton_Layout_2.addLayout(self.Botton_Layout)
        spacerItem17 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.Botton_Layout_2.addItem(spacerItem17)
        self.Botton_Layout_2.setStretch(0, 1)
        self.Botton_Layout_2.setStretch(1, 3)
        self.Botton_Layout_2.setStretch(2, 1)
        self.Control_Panel_Layout.addLayout(self.Botton_Layout_2)
        self.horizontalLayout.addLayout(self.Control_Panel_Layout)
        spacerItem18 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem18)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 19)
        self.horizontalLayout.setStretch(2, 2)
        self.horizontalLayout.setStretch(3, 8)
        self.horizontalLayout.setStretch(4, 2)
        Main_Window_UI.setCentralWidget(self.Main_Layout)

        self.retranslateUi(Main_Window_UI)
        QtCore.QMetaObject.connectSlotsByName(Main_Window_UI)

    def retranslateUi(self, Main_Window_UI):
        _translate = QtCore.QCoreApplication.translate
        Main_Window_UI.setWindowTitle(_translate("Main_Window_UI", "因为起名字好麻烦就懒得起了"))
        self.R_Lable.setText(_translate("Main_Window_UI", "R"))
        self.R_LineEdit.setText(_translate("Main_Window_UI", "255"))
        self.G_Lable.setText(_translate("Main_Window_UI", "G"))
        self.G_LineEdit.setText(_translate("Main_Window_UI", "255"))
        self.B_Lable.setText(_translate("Main_Window_UI", "B"))
        self.B_LineEdit.setText(_translate("Main_Window_UI", "255"))
        self.A_Lable.setText(_translate("Main_Window_UI", "A"))
        self.A_LineEdit.setText(_translate("Main_Window_UI", "255"))
        self.Cutout_RadioB.setText(_translate("Main_Window_UI", "抠图"))
        self.Cutout_RadioB.setShortcut(_translate("Main_Window_UI", "1"))
        self.PickColor_RadioB.setText(_translate("Main_Window_UI", "取色"))
        self.PickColor_RadioB.setShortcut(_translate("Main_Window_UI", "2"))
        self.Coloring_RadioB.setText(_translate("Main_Window_UI", "涂色"))
        self.Coloring_RadioB.setShortcut(_translate("Main_Window_UI", "3"))
        self.Filling_RadioB.setText(_translate("Main_Window_UI", "填充"))
        self.Filling_RadioB.setShortcut(_translate("Main_Window_UI", "4"))
        self.T_Lable.setText(_translate("Main_Window_UI", "容差"))
        self.T_LineEdit.setText(_translate("Main_Window_UI", "0"))
        self.S_Lable.setText(_translate("Main_Window_UI", "笔刷"))
        self.S_LineEdit.setText(_translate("Main_Window_UI", "1"))
        self.WorkDir_Button.setText(_translate("Main_Window_UI", "选择目录"))
        self.Revoke_Button.setText(_translate("Main_Window_UI", "撤销"))
        self.Revoke_Button.setShortcut(_translate("Main_Window_UI", "Ctrl+Z"))
        self.Redo_Button.setText(_translate("Main_Window_UI", "重做"))
        self.Redo_Button.setShortcut(_translate("Main_Window_UI", "Ctrl+Y"))
        self.Crop_Button.setText(_translate("Main_Window_UI", "裁剪"))
        self.Clean_Button.setText(_translate("Main_Window_UI", "清理"))
        self.Binarization_Button.setText(_translate("Main_Window_UI", "二值化"))
        self.Full_Automatic_Button.setText(_translate("Main_Window_UI", "全自动"))
        self.Semi_Automatic_Button.setText(_translate("Main_Window_UI", "半自动"))
        self.Change_Background_Button.setText(_translate("Main_Window_UI", "更换背景"))
        self.Previous_Button.setText(_translate("Main_Window_UI", "上一张"))
        self.Previous_Button.setShortcut(_translate("Main_Window_UI", "Up"))
        self.Next_Button.setText(_translate("Main_Window_UI", "下一张"))
        self.Next_Button.setShortcut(_translate("Main_Window_UI", "Down"))
        self.Save_Botton.setText(_translate("Main_Window_UI", "保存"))
        self.Save_Botton.setShortcut(_translate("Main_Window_UI", "Ctrl+S"))
from QLable_File_Dragable import QLable_File_Dragable
